apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: manuel-hennig-react-app-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: manuel-hennig-react-app
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
